name: Check and Run Tests
on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  format-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Setup dependencies
        run: npm install

      - name: Run Prettier check
        run: |
          echo "Running Prettier to check for formatting issues..."
          npm run prettier:check

      - name: Run tests
        run: npm run |
          test:delete
          test:get
          test:put